# 腾讯云函数部署

name: Tencent sls Deploy

# 触发时机
on:
  # 在 push 事件时触发工作流，但仅针对主分支
  push:
    branches: [ main ]

  # 允许您从“操作”选项卡手动运行此工作流程
  workflow_dispatch:

# 工作流运行由一个或多个可以按顺序或并行运行的作业组成
jobs:
  ################ 构建任务 #######################
  # 参考 https://github.com/swift-server/guides/blob/main/docs/packaging.md#docker
  setup-build-deploy:
    # 作业名称
    name: Setup, Build and Deploy
    # 作业: 运行时
    runs-on: ubuntu-latest
    # environment: production

    # job 运行前添加的环境变量, 部署凭证
    env:
      SERVERLESS_PLATFORM_VENDOR: tencent
      TENCENT_SECRET_ID: ${{ secrets.SECRETID }}
      TENCENT_SECRET_KEY: ${{ secrets.SECRETKEY }}

    # 步骤表示将作为作业的一部分执行的一系列任务
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # Build
      - name: 构建镜像, 并获取可执行文件压缩包
        run: |
          bash ./scripts/build_centos.sh
      
      ################## 部署任务 ########################
      - name: 安装 Serverless
        run: |
          npm install -g serverless
          npm install -g @slsplus/cli

      - name: 生成配置文件
        run: |
          slsJson=$(cat ./scf/sls.json)
          # echo $slsJson
          slsplus parse --output --auto-create --sls-options="$slsJson" && cat serverless.yml
          
      - name: 部署
        env:
          # 应用名称
          APP_NAME: ${{ secrets.APPNAME }}
          # ap-guangzhou
          REGION: ${{ secrets.REGION }}
          # Go1
          RUNTIME: ${{ secrets.RUNTIME }}
          # 实例名称 web-server
          INSTANCE_NAME: ${{ secrets.INSTANCENAME }}
        run: |
          sls deploy --force --debug

# END
